# Generated by Django 3.2.5 on 2021-07-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listall',
            name='User_department',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Отдел'),
        ),
    ]
